/*
1) Launch new Browser

2) Open URL �http://toolsqa.com/automation-practice-switch-windows/�

3) Click on Button �Alert Box�, it will open a Pop Up Window generated by JavaScript

4) Switch to Alert window (Use �SwitchTo()Alert() command)

5) Close the Pop Up Window (Use Accept command)
*/

package switchExamples;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class SwitchAlertExample {

	public static WebDriver driverName = new ChromeDriver();
	 
	public static void main(String[] args) {

        // Put an Implicit wait, this means that any search for elements on the page could take the time the implicit wait is set for before throwing exception
        driverName.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

        // Launch the URL
        driverName.get("http://toolsqa.com/automation-practice-switch-windows/");

        // Click on the Button "Alert Box"
        driverName.findElement(By.id("alert")).click();
     
        // Switch to JavaScript Alert window
        Alert myAlert = driverName.switchTo().alert();

        // Accept the Alert
        myAlert.accept();

        // Close the window
        driverName.quit();

}
}
